from cavinsmith's pull request on 2 Dec 2013
Removed command execution at case 'pageRendered' which caused TypeError
'cb' of 'pageRendered' is not a function and could not be called, so I removed call.
commit 6b3cfedce62e7dd783e921cf365b0a9e4d079a0f
parent 98b520f